path_to_trunk = '/Users/georgios_imac/mats_spec_pipeline/spectral_reduction/trunk/'

kast_blue = {'name': 'kast_blue',
			 'read_noise': 3.7,
			 'gain': 1.2,
			 'grism': 'temp',
			 'filter': 'temp',
			 'slit': 'temp',
			 'dispaxis': 1,
			 'biassec': '[1:2048,318:350]',
			 'trimsec': '[50:1900,10:300]',
			 'archive_zero_file': path_to_trunk + 'Zero_blue_20180206.fits',
			 'archive_flat_file': path_to_trunk + 'Resp_blue_20180206.fits',
			 'archive_sens': path_to_trunk + 'sens_function_blue_20180206.fits',
			 'archive_arc_extracted': path_to_trunk + 'tbb1070.ms.fits',
			 'archive_arc_extracted_id': path_to_trunk + 'id/idtbb1070.ms',
			 'line_list': path_to_trunk+'Lines_He_Hg_Cd_HgA_Ne_KAST.dat',
			 'extinction_file': path_to_trunk + 'lick_extinction.dat',
			 'observatory': 'lick',
			 'sky_file': path_to_trunk + 'licksky.fits',
			 'section': 'middle line'}


kast_red = { 'name': 'kast_red',
             'read_noise': 3.8,
			 'gain': 1.9,
			 'grism': 'temp',
			 'filter': 'temp',
			 'slit': 'temp',
			 'dispaxis': 2, 
			 'biassec': '[360:405,1:2725]',
			 'trimsec': '[60:355,125:2280]',
			 'archive_zero_file': path_to_trunk + 'Zero_red_20180206.fits',
			 'archive_flat_file': path_to_trunk + 'Resp_red_20180206.fits',
			 'archive_sens': path_to_trunk + 'sens_function_red_20180206.fits',
			 'archive_arc_extracted': path_to_trunk + 'tbr1103.ms.fits',
			 'archive_arc_extracted_id': path_to_trunk + 'id/idtbr1103.ms',
			 'line_list': path_to_trunk+'Lines_He_Hg_Cd_HgA_Ne_KAST.dat',
			 'extinction_file': path_to_trunk + 'lick_extinction.dat',
			 'observatory': 'lick',
			 'sky_file': path_to_trunk + 'licksky.fits',
			 'section': 'middle column'}